"use client";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_blocks/Header";
import { useThemeStore } from "./_state/Theme";
import { useEffect } from "react";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

/*export const metadata: Metadata = {
  title: "ByBrendan",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = useThemeStore((state) => state.theme);
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased h-full w-full  ${
          theme === "dark" ? "dark dark:bg-[#171616]" : "bg-[#F5F5F5]"
        }`}
      >
        {children}
      </body>
    </html>
  );
}
