import type { Metadata } from "next";
import { Outfit } from 'next/font/google';
import "./globals.css";
import Header from './_blocks/Header';

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
})

export const metadata: Metadata = {
  title: "ByBrendan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased h-full w-full bg-(--lightBackground)`}
      >
        {children}
      </body>
    </html>
  );
}
